name = "DruxandMarble"
author = "stygigoth"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0e80f273f0c56eb7acee7b3c8b3e43a8c650e5aeaaab6831355e9ab56486aeb"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
