name = "DruxandMarble"
author = "stygigoth"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6800405cd27a7fdd583fcdd2644cd6f0bf80f842828b99178b553ede0c9dc073"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
