name = "DruxandMarble"
author = "stygigoth"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd6da0b5f0049de4efe52f5721a97b351e832af247ba00a3e5c702ab5a5e1fe0"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
