name = "DruxandMarble"
author = "stygigoth"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae9d97b43b9a1f02507741dd09963141a635f1f8059692dbe19441f03b1e149b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
